---
- name: Run the minecraft server with non-root user.
  hosts: all
  become: no

  tasks:

  ## This part should only run the first time the Minecraft Server is set up - edit

  ## Ensure the local directory is available for Minecraft Server
  - name: Make minecraft directory
    file: path=~/minecraft state=directory
  
  ## Ensure the License Agreement is available for Minecraft Server
  - name: Get eula.txt set to true
    get_url: url=https://raw.githubusercontent.com/rzfeeser/atpb_minecraft/master/eula.txt dest=/home/minecraft/eula.txt force=yes
    
  ## Ensure the the latest version of Minecraft Server is present
  - name: Download minecraft (1.12.2)
    command: wget -O minecraft_server.jar https://s3.amazonaws.com/Minecraft.Download/versions/1.12.2/minecraft_server.1.12.2.jar chdir=~/minecraft creates=~/minecraft/minecraft_server.jar

  ## This part ensures the server is running and backed up properly
  
  ## Ensure the world is running
  - block:
      - command: pgrep java
    rescue:
      - command: "screen -dmS minecraft java -Xmx1024M -Xms1024M -jar /home/minecraft/minecraft/minecraft_server.jar nogui"

  ## Ensure that a backup directory exists on the Minecraft Server 
  - name: Make minecraft_backup directory
    file: path=~/minecraft_backup state=directory  

  ## Tell players that the world is about to go through a backup & restart
  - name: Signal the Minecraft Sever is about to go through a save cycle, and will perform a live "safe" save.
    command: "screen -S minecraft -X stuff '/say The world shall be made safe for another day. To do so. We must momentarily hault the world. Sever restart in 1 minute. \n /save-off \n /save-all \n /save-on \n'"
  
  - name: Pause for 1 minute
    pause: minutes=1
  
  ## STOP the Minecraft Server -- this also forces Screen to quit
  - name: Turn off the server so the tar file can be built without errors
    command: "screen -S minecraft -X stuff '/stop \n'"
    
  ## Sets backupdate with the date formatted as YEARMMDD (i.e 20160105 )
  - name: set date
    shell: "date +%Y%m%d"
    register: backupdate
  
  ## Build the tar file max once per day & backup to NAS & delete
  - block:
      - name: Tar up the world with the current date
        shell: "tar -cvf ~/minecraft_backup/minecraft_backup$(date +%Y%m%d).tar /home/minecraft/"
    rescue: # runs only if block fails
      - fail:
        msg: "**ATTENTION NEEDED** - The archive process has failed."
  
  ## Remove the backup directory on the Minecraft Server
  - name: Move the backups
    shell: "mv ~/minecraft_backup/*.* /tmp/"

  ## This will retrieve the backup, and move it to dest on the Ansible Tower (which should be NFS mounted storage)
  ## - name: Fetch the backup
  ##  fetch: src=~/minecraft_backup/minecraft_backup{{ backupdate.stdout }}.tar dest=server_backup/ flat=yes
  ##  fetch: src=~/minecraft_backup/minecraft_backup{{ backupdate.stdout }}.tar dest=minecraft.iris.seven//tmp/ flat=yes

  ## Ensure the world is running
  - block:
      - name: pgrep will determine if java (Minecraft Server) is running
        command: pgrep java
    rescue:
      - name: No pgrep!? Start the Minecraft Server!
        shell: "screen -dmS minecraft java -Xmx1024M -Xms1024M -jar /home/minecraft/minecraft/minecraft_server.jar nogui"

  ## Let the world know that the world has been saved!
  - name: Signal the Minecraft Sever has been backed up
    command: "screen -S minecraft -X stuff '/say Backups have been completed. Entaro Adun. \n'"
